"""Database creation

Revision ID: 95ff233f9635
Revises: 
Create Date: 2024-03-14 02:40:44.049930

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "95ff233f9635"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "referrers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("referral_code", sa.String(), nullable=True),
        sa.Column("referral_code_created", sa.DateTime(), nullable=True),
        sa.Column("referral_code_expire", sa.DateTime(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_referrers_id"), "referrers", ["id"], unique=False)
    op.create_index(
        op.f("ix_referrers_referral_code"), "referrers", ["referral_code"], unique=False
    )
    op.create_table(
        "referrals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("referral_code", sa.String(), nullable=False),
        sa.Column("referrer_id", sa.Integer(), nullable=False),
        sa.Column("referred_email", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["referrer_id"],
            ["referrers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_referrals_id"), "referrals", ["id"], unique=False)
    op.create_index(
        op.f("ix_referrals_referral_code"), "referrals", ["referral_code"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_referrals_referral_code"), table_name="referrals")
    op.drop_index(op.f("ix_referrals_id"), table_name="referrals")
    op.drop_table("referrals")
    op.drop_index(op.f("ix_referrers_referral_code"), table_name="referrers")
    op.drop_index(op.f("ix_referrers_id"), table_name="referrers")
    op.drop_table("referrers")
    # ### end Alembic commands ###
